name: Build and Test Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Cache CMake files
        uses: actions/cache@v4
        with:
          path: |
            server/build/_deps
            server/build/CMakeFiles
          key: ${{ runner.os }}-cmake-${{ hashFiles('server/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-cmake-

      - name: Build server
        run: |
          make zappy_server

      - name: Test zappy_server
        run: |
          ./zappy_server --help

      - name: Run C/C++ tests
        run: |
          cd server
          ctest

      - name: Clean up
        run: |
          make fclean
